/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.hudi.analysis

import org.apache.hudi.{HoodieSchemaConversionUtils, SparkAdapterSupport}
import org.apache.hudi.client.common.HoodieSparkEngineContext
import org.apache.hudi.client.common.SparkReaderContextFactory
import org.apache.hudi.common.config.HoodieMetadataConfig
import org.apache.hudi.common.engine.ReaderContextFactory
import org.apache.hudi.common.index.vector.{VectorIndexMdtSearchUtils, VectorIndexMetadataCache, VectorIndexOptions}
import org.apache.hudi.common.model.{FileSlice, HoodieIndexDefinition, HoodieRecord}
import org.apache.hudi.common.schema.{HoodieSchema, HoodieSchemaUtils}
import org.apache.hudi.common.table.{HoodieTableMetaClient, TableSchemaResolver}
import org.apache.hudi.common.table.read.HoodieFileGroupReader
import org.apache.hudi.common.table.view.HoodieTableFileSystemView
import org.apache.hudi.common.util.{Option => HOption}
import org.apache.hudi.data.CloseableIteratorListener
import org.apache.hudi.data.HoodieJavaRDD
import org.apache.hudi.exception.HoodieIOException
import org.apache.hudi.hadoop.fs.HadoopFSUtils
import org.apache.hudi.internal.schema.InternalSchema
import org.apache.hudi.metadata.{HoodieTableMetadata, HoodieTableMetadataUtil}

import org.apache.spark.TaskContext
import org.apache.spark.api.java.JavaSparkContext
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.{DataFrame, Row, SparkSession}
import org.apache.spark.sql.catalyst.InternalRow
import org.apache.spark.sql.catalyst.plans.logical.HoodieVectorSearchTableValuedFunction.{DistanceMetric, SearchAlgorithm}
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
import org.apache.spark.sql.expressions.Window
import org.apache.spark.sql.functions.{broadcast, col, monotonically_increasing_id, row_number}
import org.apache.spark.sql.hudi.command.exception.HoodieAnalysisException
import org.apache.spark.sql.sources.{Filter, In}
import org.apache.spark.sql.types.{ArrayType, ByteType, DataType, DoubleType, FloatType, Metadata, StructField, StructType}
import org.slf4j.LoggerFactory

import java.util.Collections

import scala.collection.JavaConverters._
import scala.collection.mutable.ArrayBuffer
import scala.util.{Failure, Success, Try}

case class VectorSearchTable(df: DataFrame, basePath: Option[String])

/**
 * Extension point for vector search algorithms. Each implementation provides
 * the Spark logical plan for single-query and batch-query KNN search.
 *
 * To add a new algorithm (e.g. RowMatrix, HNSW):
 *  1. Create an object extending this trait
 *  2. Add a value to [[SearchAlgorithm]]
 *  3. Register the mapping in [[HoodieVectorSearchPlanBuilder.resolveAlgorithm]]
 *
 * Implementations can use the shared validation helpers on
 * [[HoodieVectorSearchPlanBuilder]] (validateEmbeddingColumn, validateBatchDimensions, etc.)
 * and the raw distance functions on [[VectorDistanceUtils]].
 *
 * The output schema contract:
 *  - Single-query: all corpus columns (minus the embedding column) + `_hudi_distance: Double`
 *  - Batch-query: all corpus columns (minus the embedding column) + clashing query columns
 *    (prefixed with `_hudi_query_`) + `_hudi_distance: Double` + `_hudi_query_index: Long`
 *  - Results are ordered by `_hudi_distance` ascending (lower = more similar)
 *  - `_hudi_query_index` is an opaque grouping identifier (not a sequential index). Values may be
 *    large non-contiguous numbers because they are generated by `monotonically_increasing_id()`.
 */
trait VectorSearchAlgorithm {

  /** Human-readable name for error messages and logging. */
  def name: String

  /**
   * Build a plan that finds the k nearest corpus rows to a single query vector.
   *
   * @param spark          active SparkSession
   * @param corpusTable    resolved corpus table (may be Hudi, Parquet, or temp view)
   * @param embeddingCol   name of the array-typed embedding column in corpusDf
   * @param queryVector    the query vector, normalized to Array[Double]
   * @param k              number of nearest neighbors to return
   * @param metric         distance metric (COSINE, L2, DOT_PRODUCT)
   * @return an analyzed LogicalPlan whose output matches the single-query schema contract
   */
  def buildSingleQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      embeddingCol: String,
      queryVector: Array[Double],
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan

  /**
   * Build a plan that finds the k nearest corpus rows for each row in the query table.
   *
   * @param spark              active SparkSession
   * @param corpusTable        resolved corpus table
   * @param corpusEmbeddingCol name of the embedding column in corpusDf
   * @param queryDf            resolved query DataFrame
   * @param queryEmbeddingCol  name of the embedding column in queryDf
   * @param k                  number of nearest neighbors per query
   * @param metric             distance metric (COSINE, L2, DOT_PRODUCT)
   * @return an analyzed LogicalPlan whose output matches the batch-query schema contract
   * @note Batch mode broadcasts the query table to all executors via a cross-join.
   *       This is designed for small-to-medium query sets (tens to low hundreds of rows).
   *       For large query tables, memory pressure on executors may occur.
   */
  def buildBatchQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      corpusEmbeddingCol: String,
      queryDf: DataFrame,
      queryEmbeddingCol: String,
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan
}

/**
 * Resolves [[SearchAlgorithm]] values to [[VectorSearchAlgorithm]] implementations
 * and provides shared validation helpers used across algorithms.
 */
object HoodieVectorSearchPlanBuilder {

  private[analysis] val LOG = LoggerFactory.getLogger(getClass)

  val DISTANCE_COL = "_hudi_distance"
  private[analysis] val QUERY_ID_COL = "_hudi_query_index"
  private[analysis] val QUERY_EMB_ALIAS = "_hudi_query_emb"
  private[analysis] val RANK_COL = "_hudi_rank"
  private[analysis] val QUERY_COL_PREFIX = "_hudi_query_"

  private[analysis] def elapsedMs(startNs: Long): Long = (System.nanoTime() - startNs) / 1000000L

  private[analysis] def summarizeInts(values: Seq[Int], limit: Int = 16): String = {
    val preview = values.take(limit).mkString("[", ", ", "]")
    if (values.length > limit) s"$preview...(${values.length} total)" else preview
  }

  private[analysis] def summarizeShardCounts(shardCounts: collection.Map[Int, Int], limit: Int = 16): String = {
    val preview = shardCounts.toSeq.sortBy(_._1).take(limit).map { case (clusterId, count) =>
      s"$clusterId->$count"
    }.mkString("[", ", ", "]")
    if (shardCounts.size > limit) s"$preview...(${shardCounts.size} total)" else preview
  }

  private[analysis] def logRddLineage(label: String, rdd: RDD[_]): Unit = {
    Try(rdd.toDebugString) match {
      case Success(debug) =>
        LOG.info(s"[vector_search][$label] lineage:\n$debug")
      case Failure(error) =>
        LOG.warn(s"[vector_search][$label] unable to fetch RDD lineage", error)
    }
  }

  /** Resolve a [[SearchAlgorithm]] enum value to its implementation. */
  def resolveAlgorithm(algorithm: SearchAlgorithm.Value): VectorSearchAlgorithm = algorithm match {
    case SearchAlgorithm.BRUTE_FORCE => BruteForceSearchAlgorithm
    case SearchAlgorithm.IVF_RABITQ_MDT => IvfRaBitQMdtSearchAlgorithm
    case other => throw new HoodieAnalysisException(
      s"Unsupported search algorithm: $other")
  }

  private[analysis] def validateEmbeddingColumn(df: DataFrame, colName: String): Unit = {
    val fieldOpt = df.schema.fields.find(_.name.equalsIgnoreCase(colName))
    val field = fieldOpt.getOrElse(
      throw new HoodieAnalysisException(
        s"Embedding column '$colName' not found in table schema. " +
          s"Available columns: ${df.schema.fieldNames.mkString(", ")}"))
    field.dataType match {
      case ArrayType(FloatType, _) | ArrayType(DoubleType, _) | ArrayType(ByteType, _) => // valid
      case other =>
        throw new HoodieAnalysisException(
          s"Embedding column '$colName' has type $other, " +
            "expected array<float>, array<double>, or array<byte>")
    }
  }

  /**
   * Validates that the query vector dimension matches the corpus embedding dimension
   * when the corpus column has VECTOR(dim) metadata.
   */
  private[analysis] def validateQueryVectorDimension(
      df: DataFrame, embeddingCol: String, queryDim: Int): Unit = {
    extractVectorSchema(df, embeddingCol).map(_.getDimension).foreach { corpusDim =>
      if (corpusDim != queryDim) {
        throw new HoodieAnalysisException(
          s"Query vector dimension ($queryDim) does not match " +
            s"corpus embedding dimension ($corpusDim) for column '$embeddingCol'")
      }
    }
  }

  /**
   * Validates that corpus and query embedding columns have the same element type.
   *
   * This is a deliberate design choice: we require strict type matching rather than
   * silently upcasting (e.g. float to double). While some vector search systems
   * auto-convert, strict matching avoids subtle precision differences and makes
   * type mismatches between pipelines explicit. This can be relaxed to support
   * automatic widening (byte -> float -> double) in a future iteration if needed.
   */
  private[analysis] def validateElementTypeCompatibility(
      corpusDf: DataFrame, corpusCol: String,
      queryDf: DataFrame, queryCol: String): Unit = {
    val corpusElemType = getElementType(corpusDf, corpusCol)
    val queryElemType = getElementType(queryDf, queryCol)
    if (corpusElemType != queryElemType) {
      throw new HoodieAnalysisException(
        s"Corpus embedding column '$corpusCol' has element type $corpusElemType " +
          s"but query embedding column '$queryCol' has element type $queryElemType. " +
          "Both must use the same element type (e.g. array<float>).")
    }
  }

  /**
   * Validates that corpus and query embedding dimensions match when both have
   * VECTOR(dim) metadata.
   */
  private[analysis] def validateBatchDimensions(
      corpusDf: DataFrame, corpusCol: String,
      queryDf: DataFrame, queryCol: String): Unit = {
    (extractVectorSchema(corpusDf, corpusCol).map(_.getDimension), extractVectorSchema(queryDf, queryCol).map(_.getDimension)) match {
      case (Some(corpusDim), Some(queryDim)) if corpusDim != queryDim =>
        throw new HoodieAnalysisException(
          s"Corpus embedding dimension ($corpusDim) does not match " +
            s"query embedding dimension ($queryDim)")
      case _ => // dimensions match or metadata not available
    }
  }

  private[analysis] def getElementType(df: DataFrame, colName: String): DataType = {
    val field = df.schema.fields.find(_.name.equalsIgnoreCase(colName)).getOrElse(
      throw new HoodieAnalysisException(
        s"Embedding column '$colName' not found in table schema. " +
          s"Available columns: ${df.schema.fieldNames.mkString(", ")}"))
    field.dataType match {
      case ArrayType(elemType, _) => elemType
      case other =>
        throw new HoodieAnalysisException(
          s"Embedding column '$colName' has type $other, expected an array type")
    }
  }

  /** Extracts VECTOR schema from column metadata, if present. */
  private[analysis] def extractVectorSchema(df: DataFrame, colName: String): Option[HoodieSchema.Vector] = {
    df.schema.fields.find(_.name.equalsIgnoreCase(colName)).flatMap { field =>
      val meta = field.metadata
      if (meta.contains(HoodieSchema.TYPE_METADATA_FIELD)) {
        val typeDesc = meta.getString(HoodieSchema.TYPE_METADATA_FIELD)
        Try(HoodieSchema.parseTypeDescriptor(typeDesc)) match {
          case Success(v: HoodieSchema.Vector) => Some(v)
          case Success(_) => throw new HoodieAnalysisException(
            s"Column '$colName' has type '$typeDesc' which is not a VECTOR type. " +
              "Only VECTOR columns are supported for vector search.")
          case Failure(e) => throw new HoodieAnalysisException(
            s"Column '$colName' has malformed type metadata '$typeDesc': ${e.getMessage}")
        }
      } else None
    }
  }

  private[analysis] def quoteIdentifier(name: String): String = s"`${name.replace("`", "``")}`"
}

/**
 * Brute-force KNN vector search: computes distance between every corpus row and
 * every query vector, then selects the top-K closest.
 *
 * <p>Complexity: O(|corpus| * |queries| * dimensions) — linear scan with no index.
 *
 * <p><b>Single-query mode:</b> applies a distance UDF per corpus row, then
 * {@code orderBy + limit(k)} (Spark optimizes this to a partial sort via TakeOrderedAndProject).
 *
 * <p><b>Batch-query mode:</b> broadcast cross-joins the (small) query table with
 * the corpus, computes pairwise distances, then uses a window function to rank
 * and select top-K per query. The cross-join produces O(|corpus| * |queries|)
 * intermediate rows, so this is suitable for small-to-medium query sets
 * (tens to low hundreds of queries) against moderate corpora.
 */
object BruteForceSearchAlgorithm extends VectorSearchAlgorithm {

  import HoodieVectorSearchPlanBuilder._

  override val name: String = "brute_force"

  override def buildSingleQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      embeddingCol: String,
      queryVector: Array[Double],
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan = {
    val corpusDf = corpusTable.df
    validateEmbeddingColumn(corpusDf, embeddingCol)
    validateQueryVectorDimension(corpusDf, embeddingCol, queryVector.length)

    val elemType = getElementType(corpusDf, embeddingCol)
    val filteredDf = corpusDf.filter(col(embeddingCol).isNotNull)

    // Validate byte corpus query vector values before creating the UDF.
    if (elemType == ByteType) {
      queryVector.foreach { v =>
        if (v < Byte.MinValue || v > Byte.MaxValue)
          throw new HoodieAnalysisException(
            s"Query vector value $v is out of range for byte corpus [${Byte.MinValue}, ${Byte.MaxValue}]")
        if (v != v.toByte.toDouble)
          throw new HoodieAnalysisException(
            s"Query vector value $v is not a whole number. " +
              "Byte corpus embeddings require integer-valued query vectors.")
      }
    }

    // The single-query UDF closes over the pre-computed query DenseVector,
    // so only the corpus column is passed per row.
    val distanceUdf = VectorDistanceUtils.createSingleQueryDistanceUdf(metric, elemType, queryVector)

    val result = filteredDf
      .withColumn(DISTANCE_COL, distanceUdf(col(embeddingCol)))
      .drop(embeddingCol)
      .orderBy(col(DISTANCE_COL).asc)
      .limit(k)

    result.queryExecution.analyzed
  }

  override def buildBatchQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      corpusEmbeddingCol: String,
      queryDf: DataFrame,
      queryEmbeddingCol: String,
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan = {
    val corpusDf = corpusTable.df
    validateEmbeddingColumn(corpusDf, corpusEmbeddingCol)
    validateEmbeddingColumn(queryDf, queryEmbeddingCol)
    validateElementTypeCompatibility(corpusDf, corpusEmbeddingCol, queryDf, queryEmbeddingCol)
    validateBatchDimensions(corpusDf, corpusEmbeddingCol, queryDf, queryEmbeddingCol)

    val corpusElemType = getElementType(corpusDf, corpusEmbeddingCol)
    val distanceUdf = VectorDistanceUtils.createDistanceUdf(metric, corpusElemType)
    val filteredCorpus = corpusDf.filter(col(corpusEmbeddingCol).isNotNull)

    // Prefix clashing query columns with "_hudi_query_" to avoid cross-join ambiguity when
    // corpus and query share column names (e.g. both have "id" or "embedding").
    val corpusCols = filteredCorpus.columns.toSet
    val queryWithId = queryDf.filter(col(queryEmbeddingCol).isNotNull)
      .withColumnRenamed(queryEmbeddingCol, QUERY_EMB_ALIAS)
      .withColumn(QUERY_ID_COL, monotonically_increasing_id())

    val renamedQuery = queryWithId.select(queryWithId.columns.map { qCol =>
      if (qCol != QUERY_ID_COL && qCol != QUERY_EMB_ALIAS && corpusCols.contains(qCol))
        col(qCol).as(s"$QUERY_COL_PREFIX$qCol")
      else
        col(qCol)
    }: _*)

    // Cross join corpus with broadcast queries, compute distance, then rank
    val scored = filteredCorpus.crossJoin(broadcast(renamedQuery))
      .withColumn(DISTANCE_COL,
        distanceUdf(col(corpusEmbeddingCol), col(QUERY_EMB_ALIAS)))
      .drop(corpusEmbeddingCol)
      .drop(QUERY_EMB_ALIAS)

    val window = Window.partitionBy(QUERY_ID_COL).orderBy(col(DISTANCE_COL).asc)
    val result = scored
      .withColumn(RANK_COL, row_number().over(window))
      .filter(col(RANK_COL) <= k)
      .drop(RANK_COL)
      .orderBy(col(QUERY_ID_COL), col(DISTANCE_COL))

    result.queryExecution.analyzed
  }

}

/**
 * IVF + RaBitQ vector search backed by native metadata-table posting prefix lookups.
 *
 * The algorithm keeps Spark SQL out of the posting scan: it probes centroids, converts
 * the selected clusters to MDT posting prefixes, reads posting rows with HFile-friendly
 * prefix lookups, reduces with RaBitQ approximate scores before record-location lookup,
 * then exact-reranks the fetched Hudi rows.
 */
object IvfRaBitQMdtSearchAlgorithm extends VectorSearchAlgorithm with SparkAdapterSupport {

  import HoodieVectorSearchPlanBuilder._

  override val name: String = "ivf_rabitq_mdt"

  override def buildSingleQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      embeddingCol: String,
      queryVector: Array[Double],
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan = {
    val corpusDf = corpusTable.df
    validateEmbeddingColumn(corpusDf, embeddingCol)
    validateQueryVectorDimension(corpusDf, embeddingCol, queryVector.length)

    val basePath = corpusTable.basePath.getOrElse {
      throw new HoodieAnalysisException(
        s"Search algorithm '$name' requires a Hudi table identifier or table path, not a temporary view.")
    }
    if (!corpusDf.columns.contains(HoodieRecord.RECORD_KEY_METADATA_FIELD)) {
      throw new HoodieAnalysisException(
        s"Search algorithm '$name' requires Hudi meta fields, but '${HoodieRecord.RECORD_KEY_METADATA_FIELD}' is missing.")
    }

    val vectorSchema = extractVectorSchema(corpusDf, embeddingCol).getOrElse {
      throw new HoodieAnalysisException(
        s"Search algorithm '$name' requires '$embeddingCol' to carry VECTOR metadata.")
    }
    val queryFloat = queryVector.map(_.toFloat)

    val metaClient = HoodieTableMetaClient.builder()
      .setConf(HadoopFSUtils.getStorageConf(spark.sessionState.newHadoopConf()).newInstance())
      .setBasePath(basePath)
      .build()
    val (_, indexDefinition) = resolveVectorIndexDefinition(metaClient, embeddingCol)
    val indexOptions = Option(indexDefinition.getIndexOptions).map(_.asScala.toMap).getOrElse(Map.empty)
    val mergedOptions = indexOptions ++ runtimeOptions
    val approxMode = VectorIndexOptions.isApproximateSearchMode(mergedOptions.asJava)

    if (approxMode) {
      buildApproximatePlan(spark, basePath, queryFloat, embeddingCol, vectorSchema, k)
    } else {
      val elemType = getElementType(corpusDf, embeddingCol)
      val distanceUdf = VectorDistanceUtils.createSingleQueryDistanceUdf(metric, elemType, queryVector)

      val candidateDf = buildRaBitQExactCandidateDf(spark, basePath, corpusDf.schema, embeddingCol, vectorSchema, queryFloat, k)
      val baseAlias = "base"
      val joined = candidateDf.as(baseAlias)
        .withColumn(DISTANCE_COL, distanceUdf(col(s"$baseAlias.${quoteIdentifier(embeddingCol)}")))

      val resultColumns = corpusDf.columns
        .filterNot(_.equalsIgnoreCase(embeddingCol))
        .map(c => col(s"$baseAlias.${quoteIdentifier(c)}")) :+ col(DISTANCE_COL)

      joined
        .select(resultColumns: _*)
        .orderBy(col(DISTANCE_COL).asc)
        .limit(k)
        .queryExecution.analyzed
    }
  }

  override def buildBatchQueryPlan(
      spark: SparkSession,
      corpusTable: VectorSearchTable,
      corpusEmbeddingCol: String,
      queryDf: DataFrame,
      queryEmbeddingCol: String,
      k: Int,
      metric: DistanceMetric.Value,
      runtimeOptions: Map[String, String] = Map.empty): LogicalPlan = {
    throw new HoodieAnalysisException(
      s"Search algorithm '$name' currently supports single-query hudi_vector_search only.")
  }

  /**
   * Approximate-only path: scores postings via RaBitQ and returns
   * (record_key, partition_path, file_group_id, approx_distance) without
   * reading the base table at all.
   */
  private def buildApproximatePlan(
      spark: SparkSession,
      basePath: String,
      queryVector: Array[Float],
      embeddingCol: String,
      vectorSchema: HoodieSchema.Vector,
      k: Int): LogicalPlan = {
    import spark.implicits._
    val planStartNs = System.nanoTime()
    val storageConf = HadoopFSUtils.getStorageConf(spark.sessionState.newHadoopConf())
    val metaClient = HoodieTableMetaClient.builder()
      .setConf(storageConf.newInstance())
      .setBasePath(basePath)
      .build()
    val (indexPartition, indexDefinition) = resolveVectorIndexDefinition(metaClient, embeddingCol)
    val indexOptions = Option(indexDefinition.getIndexOptions).map(_.asScala.toMap).getOrElse(Map.empty)

    val metadataConfig = HoodieMetadataConfig.newBuilder().enable(true).build()
    val engineContext = new HoodieSparkEngineContext(new JavaSparkContext(spark.sparkContext), spark.sqlContext)
    val metadataTable = metaClient.getTableFormat.getMetadataFactory
      .create(engineContext, metaClient.getStorage, metadataConfig, basePath)
    val cache = getOrLoadMetadataCache(metaClient, metadataTable, indexPartition, vectorSchema)
    if (cache == null || cache.getGenerationId < 0) {
      throw new HoodieAnalysisException(
        s"Vector index '$indexPartition' does not contain valid metadata for approximate search.")
    }

    val metric = VectorIndexOptions.getMetric(indexOptions.asJava)
    val numProbes = math.min(math.max(1, VectorIndexOptions.getNumProbes(indexOptions.asJava)), cache.numClusters())
    val topClusters = cache.findTopClusters(queryVector, numProbes, metric)
    val shardCounts = cache.getShardCounts(topClusters)
    val refineK = math.max(k, k * VectorIndexOptions.getRefineFactor(indexOptions.asJava))
    val postings = VectorIndexMdtSearchUtils.readPostingMatches(
      metadataTable, indexPartition, cache.getGenerationId, shardCounts, false)

    val scored = VectorIndexMdtSearchUtils.scorePostingMatches(
      postings, queryVector, cache.getDimension, cache.getQuantizerSeed, cache.isAssumeNormalized)
    val topCandidates = VectorIndexMdtSearchUtils.selectTopK(scored, refineK)
    val resultSchema = new StructType(Array(
      StructField(HoodieRecord.RECORD_KEY_METADATA_FIELD, org.apache.spark.sql.types.DataTypes.StringType, nullable = false, Metadata.empty),
      StructField(HoodieRecord.PARTITION_PATH_METADATA_FIELD, org.apache.spark.sql.types.DataTypes.StringType, nullable = true, Metadata.empty),
      StructField("_hudi_file_group_id", org.apache.spark.sql.types.DataTypes.StringType, nullable = true, Metadata.empty),
      StructField(DISTANCE_COL, org.apache.spark.sql.types.DataTypes.DoubleType, nullable = false, Metadata.empty)
    ))
    val resultRows = HoodieJavaRDD.getJavaRDD(topCandidates).rdd.map { c =>
      Row(
        c.getRecordKey,
        Option(c.getPartitionPath).getOrElse(""),
        Option(c.getFileGroupId).getOrElse(""),
        c.getApproxDistance.toDouble
      )
    }
    LOG.info(s"[vector_search][approximate] basePath=$basePath probedClusters=${topClusters.length} planMs=${elapsedMs(planStartNs)}")
    spark.createDataFrame(resultRows, resultSchema)
      .orderBy(col(DISTANCE_COL).asc)
      .limit(k)
      .queryExecution.analyzed
  }

  private def buildRaBitQExactCandidateDf(
      spark: SparkSession,
      basePath: String,
      outputSchema: StructType,
      embeddingCol: String,
      vectorSchema: HoodieSchema.Vector,
      queryVector: Array[Float],
      k: Int): DataFrame = {
    val planStartNs = System.nanoTime()
    val storageConf = HadoopFSUtils.getStorageConf(spark.sessionState.newHadoopConf())
    val metaClient = HoodieTableMetaClient.builder()
      .setConf(storageConf.newInstance())
      .setBasePath(basePath)
      .build()
    val (indexPartition, indexDefinition) = resolveVectorIndexDefinition(metaClient, embeddingCol)
    val indexOptions = Option(indexDefinition.getIndexOptions).map(_.asScala.toMap).getOrElse(Map.empty)
    val dimension = VectorIndexOptions.getDimension(indexOptions.asJava)
    if (dimension != vectorSchema.getDimension) {
      throw new HoodieAnalysisException(
        s"Vector index dimension ($dimension) does not match column '$embeddingCol' dimension (${vectorSchema.getDimension}).")
    }

    val metadataConfig = HoodieMetadataConfig.newBuilder().enable(true).build()
    val engineContext = new HoodieSparkEngineContext(new JavaSparkContext(spark.sparkContext), spark.sqlContext)
    val metadataTable = metaClient.getTableFormat.getMetadataFactory
      .create(engineContext, metaClient.getStorage, metadataConfig, basePath)
    val cacheLoadStartNs = System.nanoTime()
    val cache = getOrLoadMetadataCache(metaClient, metadataTable, indexPartition, vectorSchema)
    if (cache == null) {
      throw new HoodieAnalysisException(
        s"Vector index '$indexPartition' does not contain cacheable centroid metadata.")
    }
    if (cache.getGenerationId < 0) {
      throw new HoodieAnalysisException(
        s"Vector index '$indexPartition' does not contain generation metadata.")
    }

    val metric = VectorIndexOptions.getMetric(indexOptions.asJava)
    val numProbes = math.min(math.max(1, VectorIndexOptions.getNumProbes(indexOptions.asJava)), cache.numClusters())
    val topClusters = cache.findTopClusters(queryVector, numProbes, metric)
    val topClusterSeq = topClusters.toSeq
    val cacheLoadMs = elapsedMs(cacheLoadStartNs)

    // Shard counts from cache — no extra MDT IO.
    val shardCounts = cache.getShardCounts(topClusters)
    val shardCountsScala = shardCounts.asScala.map { case (clusterId, count) =>
      clusterId.intValue() -> count.intValue()
    }.toMap
    val postingPrefixCount = VectorIndexMdtSearchUtils.buildPostingPrefixes(cache.getGenerationId, shardCounts).size()
    LOG.info(
      s"[vector_search][plan] basePath=$basePath indexPartition=$indexPartition cacheLoadMs=$cacheLoadMs " +
        s"generationId=${cache.getGenerationId} dimension=${cache.getDimension} numClusters=${cache.numClusters()} " +
        s"numProbes=$numProbes refineFactor=${VectorIndexOptions.getRefineFactor(indexOptions.asJava)} " +
        s"topClusters=${summarizeInts(topClusterSeq)} shardCounts=${summarizeShardCounts(shardCountsScala)} " +
        s"postingPrefixes=$postingPrefixCount")
    if (shardCounts.isEmpty) {
      sparkAdapter.getUnsafeUtils.createDataFrameFromRDD(
        spark, spark.sparkContext.emptyRDD[InternalRow], outputSchema)
    } else {
      val timeline = metaClient.getActiveTimeline.getCommitsAndCompactionTimeline.filterCompletedInstants()
      val latestInstant = timeline.lastInstant().orElseThrow(() =>
        new HoodieAnalysisException(s"No completed commits found for table '${metaClient.getBasePath}'."))
      val latestInstantTime = latestInstant.requestedTime()

      val candidateFgIds = cache.getFileGroupsForClusters(topClusters, null)
      val fileSliceMap = preResolveFileSlices(
        metadataTable, metaClient, timeline, latestInstantTime, candidateFgIds)
      val bFileSliceMap = spark.sparkContext.broadcast(fileSliceMap)

      val tableSchemaWithMetaFields = HoodieSchemaUtils.addMetadataFields(
        new TableSchemaResolver(metaClient).getTableSchema(false), false)
      val requestedFieldNames = outputSchema.fieldNames.toSeq.distinct
      val requestedSchemaWithMetaFields = HoodieSchemaUtils.projectSchema(tableSchemaWithMetaFields, requestedFieldNames.asJava)
      val requestedSparkSchema = HoodieSchemaConversionUtils.convertHoodieSchemaToStructType(requestedSchemaWithMetaFields)
      val readerContextFactory = engineContext.getReaderContextFactory(metaClient)
        .asInstanceOf[ReaderContextFactory[InternalRow]]
      val sparkReaderContextFactory = readerContextFactory.asInstanceOf[SparkReaderContextFactory]
      val recordKeyOrdinal = requestedSparkSchema.fieldIndex(HoodieRecord.RECORD_KEY_METADATA_FIELD)

      val refineK = math.max(k, k * VectorIndexOptions.getRefineFactor(indexOptions.asJava))
      val emptyDf = sparkAdapter.getUnsafeUtils.createDataFrameFromRDD(
        spark, spark.sparkContext.emptyRDD[InternalRow], requestedSparkSchema)

      val postings = VectorIndexMdtSearchUtils.readPostingMatches(
        metadataTable, indexPartition, cache.getGenerationId, shardCounts, false)
      val scored = VectorIndexMdtSearchUtils.scorePostingMatches(
        postings, queryVector, cache.getDimension, cache.getQuantizerSeed, cache.isAssumeNormalized)
      val topCandidates = VectorIndexMdtSearchUtils.selectTopK(scored, refineK)
      val topKRdd = HoodieJavaRDD.getJavaRDD(topCandidates).rdd
        .filter(_.getFileGroupId != null)

      if (topKRdd.isEmpty()) {
        bFileSliceMap.destroy()
        emptyDf
      } else {
        val exactFetchParallelism = math.max(
          1,
          math.min(refineK, math.max(1, spark.sparkContext.defaultParallelism * 4)))
        val byFileGroup: RDD[(String, Iterable[VectorIndexMdtSearchUtils.ScoredPostingMatch])] = topKRdd
          .keyBy(_.getFileGroupId)
          .groupByKey(exactFetchParallelism)
        LOG.info(
          s"[vector_search][stage][exact_read_plan] topKPartitions=${topKRdd.getNumPartitions} " +
            s"fileGroupPartitions=${byFileGroup.getNumPartitions} exactFetchParallelism=$exactFetchParallelism")

        val exactRows: RDD[InternalRow] = byFileGroup.mapPartitions { groups =>
          val startNs = System.nanoTime()
          val rows = ArrayBuffer.empty[InternalRow]
          var groupCount = 0
          var resolvedSlices = 0
          var missingSlices = 0
          var candidateKeys = 0L
          var matchedRows = 0L
          var bytesReadFromObjectStore = 0L
          var parquetBytesRead = 0L
          var baseFiles = 0
          var logFiles = 0L
          var totalSliceBytes = 0L
          while (groups.hasNext) {
            val (fgId, candidates) = groups.next()
            groupCount += 1
            val fileSliceOpt = bFileSliceMap.value.get(fgId)
            if (fileSliceOpt.isEmpty) {
              missingSlices += 1
            } else {
              resolvedSlices += 1
              val fileSlice = fileSliceOpt.get
              val recordKeys = candidates.map(_.getRecordKey).toSet
              candidateKeys += recordKeys.size
              if (fileSlice.getBaseFile.isPresent) {
                baseFiles += 1
              }
              logFiles += fileSlice.getLogFiles.count()
              totalSliceBytes += fileSlice.getTotalFileSize
              val recordKeyFilter: Filter = In(HoodieRecord.RECORD_KEY_METADATA_FIELD, recordKeys.toArray[Any])
              val readerContext = sparkReaderContextFactory.getContext(Collections.singletonList(recordKeyFilter))
              readerContext.setTablePath(basePath)
              readerContext.setLatestCommitTime(latestInstantTime)
              val taskMetaClient = HoodieTableMetaClient.builder()
                .setConf(storageConf.newInstance())
                .setBasePath(basePath)
                .build()
              val fileGroupReader = HoodieFileGroupReader.newBuilder[InternalRow]()
                .withReaderContext(readerContext)
                .withHoodieTableMetaClient(taskMetaClient)
                .withLatestCommitTime(latestInstantTime)
                .withFileSlice(fileSlice)
                .withDataSchema(tableSchemaWithMetaFields)
                .withRequestedSchema(requestedSchemaWithMetaFields)
                .withInternalSchema(HOption.empty[InternalSchema]())
                .withProps(taskMetaClient.getTableConfig.getProps)
                .withShouldUseRecordPosition(false)
                .build()
              try {
                val inputMetrics = Option(TaskContext.get()).map(_.taskMetrics().inputMetrics)
                val bytesBefore = inputMetrics.map(_.bytesRead).getOrElse(0L)
                val iterator = fileGroupReader.getClosableIterator
                CloseableIteratorListener.addListener(iterator)
                try {
                  while (iterator.hasNext) {
                    val row = iterator.next()
                    if (recordKeys.contains(row.getString(recordKeyOrdinal))) {
                      rows += row.copy()
                      matchedRows += 1
                    }
                  }
                } finally {
                  iterator.close()
                }
                val bytesAfter = inputMetrics.map(_.bytesRead).getOrElse(bytesBefore)
                val bytesDelta = math.max(0L, bytesAfter - bytesBefore)
                bytesReadFromObjectStore += bytesDelta
                parquetBytesRead += bytesDelta
              } catch {
                case ioe: java.io.IOException =>
                  throw new HoodieIOException(
                    s"Unable to read vector candidate file group $fgId", ioe)
              }
            }
          }
          LOG.info(
            s"[vector_search][stage][exact_read] candidateRecordCount=$candidateKeys candidateFileCount=$resolvedSlices " +
              s"candidateRowGroupCount=unknown groups=$groupCount resolvedSlices=$resolvedSlices missingSlices=$missingSlices " +
              s"bytesReadFromObjectStore=$bytesReadFromObjectStore parquetBytesRead=$parquetBytesRead rowsReturned=$matchedRows " +
              s"rowGroupsSkipped=unknown rowGroupsRead=unknown baseFiles=$baseFiles logFiles=$logFiles " +
              s"sliceBytes=$totalSliceBytes columnsRequested=${requestedFieldNames.mkString("[", ", ", "]")} elapsedMs=${elapsedMs(startNs)}")
          rows.iterator
        }
        LOG.info(s"[vector_search][plan] exact candidate DF planned in ${elapsedMs(planStartNs)} ms")
        sparkAdapter.getUnsafeUtils.createDataFrameFromRDD(spark, exactRows, requestedSparkSchema)
      }
    }
  }

  private def preResolveFileSlices(
      metadataTable: HoodieTableMetadata,
      metaClient: HoodieTableMetaClient,
      timeline: org.apache.hudi.common.table.timeline.HoodieTimeline,
      latestInstantTime: String,
      candidateFgIds: java.util.Set[String]): Map[String, FileSlice] = {
    val startNs = System.nanoTime()
    val fsView = new HoodieTableFileSystemView(metadataTable, metaClient, timeline)
    try {
      fsView.loadAllPartitions()
      val result = scala.collection.mutable.Map.empty[String, FileSlice]
      val fgIter = fsView.getAllFileGroups.iterator()
      var baseFiles = 0
      var logFiles = 0L
      var totalSliceBytes = 0L
      while (fgIter.hasNext) {
        val fg = fgIter.next()
        if (candidateFgIds.contains(fg.getFileGroupId.getFileId)) {
          val sliceOpt = fg.getLatestFileSliceBeforeOrOn(latestInstantTime)
          if (sliceOpt.isPresent) {
            val slice = sliceOpt.get()
            result(fg.getFileGroupId.getFileId) = slice
            if (slice.getBaseFile.isPresent) {
              baseFiles += 1
            }
            logFiles += slice.getLogFiles.count()
            totalSliceBytes += slice.getTotalFileSize
          }
        }
      }
      LOG.info(
        s"[vector_search][stage][resolve_file_slices] candidateFileGroups=${candidateFgIds.size} resolvedSlices=${result.size} " +
          s"baseFiles=$baseFiles logFiles=$logFiles sliceBytes=$totalSliceBytes elapsedMs=${elapsedMs(startNs)}")
      result.toMap
    } finally {
      fsView.close()
    }
  }

  private def resolveVectorIndexDefinition(
      metaClient: HoodieTableMetaClient,
      embeddingCol: String): (String, HoodieIndexDefinition) = {
    if (!metaClient.getIndexMetadata.isPresent) {
      throw new HoodieAnalysisException("No Hudi index metadata is available for the table.")
    }
    val matches = metaClient.getIndexMetadata.get.getIndexDefinitions.asScala
      .filter { case (_, definition) =>
        definition.getIndexType == HoodieTableMetadataUtil.PARTITION_NAME_VECTOR_INDEX
      }
      .filter { case (_, definition) =>
        Option(definition.getSourceFields).exists(_.asScala.exists(_.equalsIgnoreCase(embeddingCol)))
      }
      .toSeq
      .sortBy(_._1)
    matches.headOption.getOrElse {
      throw new HoodieAnalysisException(
        s"No vector index found for embedding column '$embeddingCol'.")
    }
  }

  private case class MetadataCacheKey(basePath: String, indexPartition: String)

  @volatile private var metadataCaches: Map[MetadataCacheKey, VectorIndexMetadataCache] = Map.empty

  private[analysis] def resetMetadataCaches(): Unit = {
    metadataCaches = Map.empty
  }

  private[analysis] def metadataCacheSize: Int = metadataCaches.size

  private def getOrLoadMetadataCache(
      metaClient: HoodieTableMetaClient,
      metadataTable: HoodieTableMetadata,
      indexPartition: String,
      vectorSchema: HoodieSchema.Vector): VectorIndexMetadataCache = {
    val cacheKey = MetadataCacheKey(metaClient.getBasePath.toString, indexPartition)
    val currentInstant = metaClient.getActiveTimeline.lastInstant().map[String](_.requestedTime()).orElse("")

    metadataCaches.get(cacheKey) match {
      case Some(existing) if !existing.isStaleFor(currentInstant) => existing
      case _ =>
        // Full cache: centroids, manifest, quantizer, AND cluster manifests.
        // Cluster manifests are ~K rows (~200 KB for 4096 clusters) and stable
        // until rebuild. Caching them eliminates the per-query readClusterShardCounts
        // MDT IO and avoids extra cluster-manifest lookups on the query hot path.
        val loaded = VectorIndexMetadataCache.load(metadataTable, indexPartition, vectorSchema, currentInstant, true)
        if (loaded != null) {
          metadataCaches = metadataCaches.updated(cacheKey, loaded)
        }
        loaded
    }
  }
}
